### PR TITLE
Windows 10 Technical Preview Build 9926

### PR DESCRIPTION
**Pull request by StefanScherer**
After retesting the Build 9926 of Windows 10 Technical Preview I found out that floppy support is back again.
So I gave packer a try and only some IMAGE/NAME adjustments were needed to make the packer build work.

Tested with VMware Fusion 6.0.4.

### CODE REVIEW

**Comment by joefitzgerald** [comment]
LGTM - @StefanScherer feel free to merge (you don't actually need an LGTM from me to do that :wink:).

**Comment by StefanScherer** [comment]
@joefitzgerald thanks for the compliment, but I just can send PR's which is fine for me ;-)

**Comment by staxmanade** [comment]
Any thoughts as to why this has not yet been merged? Are there outstanding issues?

**Comment by StefanScherer** [comment]
Triggering @joefitzgerald @kensykora to merge it ;-)

**Comment by joefitzgerald** [comment]
@stefanscherer you should feel free to merge anything you think is worthy.

**Comment by StefanScherer** [comment]
@joefitzgerald Thanks for the honor. Feel free to add me as a collaborator to this repo, so I'm able to merge :smiley:

**Comment by jcoutch** [comment]
Just fought to get 10074 working with Packer.  I found if you take the Windows 8.1 file, set the product key to the following (form the tech preview page):

```
<ProductKey>6P99N-YF42M-TPGBG-9VMJP-YKHCF
    <WillShowUI>Never</WillShowUI>
</ProductKey>
```

And set the InstallFrom\Value key to: `Windows 10 Pro Technical Preview`

It works!  For when the full release comes out next month, just run `dism /get-wiminfo /wimfile:d:\sources\install.wim` to get the new description, jam in your product key, and you're good to go! :-)

**Comment by StefanScherer** [comment]
@jcoutch thanks for sharing. It's already in the `develop` branch with this commit https://github.com/joefitzgerald/packer-windows/pull/144/files

**Comment by joefitzgerald** [comment]
@StefanScherer do you think we should do away with the develop / master bifurcation?

**Comment by StefanScherer** [comment]
@joefitzgerald at least we should merge develop to master as there are plenty improvements in there. 

If you want me to help, just add me as collab. 

Am 06.06.2015 um 21:16 schrieb Joe Fitzgerald <notifications@github.com>:

**Comment by joefitzgerald** [comment]
Done.

**Pull request merged**
