### PR TITLE
Added atlas push support

### PR DESCRIPTION
**Pull request by MOZGIII**
When pushing to atlas use gitignore to track ignored files and not load them

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Does this play nice if someone is *not* using Atlas?

**Comment by MOZGIII** [comment]
It only matters if you ever use push comand, hich is afaik used only with atlas.

**Comment by senglin** [comment]
@MOZGIII I could never get packer push to automatically build and register the vbox file in atlas. Are the configurations made sufficient for anyone to push to Atlas? If there still needs or other configuration (i.e. token, setting environment variables), it would be nice to have commented examples within the script.

**Comment by MOZGIII** [comment]
It's just a tiny bit of improvement for atlas support. By default it tries to upload all files, including `iso`s and `packer_cache`, which are bigger than `5gb`, which is maximum *upload* allowed by atlas.

To provide full support we probably need to add atlas `post_processors`, however I don't have a settled idea on how to implement it public-repo-friendly way, cause besides token, which is used from the environment by default (which is ok), there is also atlas vagrant repo name, which includes particular username, and that does not allow for easy sharing.

**Comment by sneal** [comment]
Closing this, but I'll merge it into #200.

**Comment by MOZGIII** [comment]
Great!

**Pull request closed without merging**
