### PR TITLE
fix vbox guest tool silent installation on windows due to pending certs

### PR DESCRIPTION
**Pull request by lmayorga1980**
I had issues deploying the VBoxGuest tools with VBox 5.1.22 and this fixed the issue.

### CODE REVIEW

**Comment by Flauschbaellchen** [comment]
I fixed this by adding
```bash
cmd /c for %%i in (C:\Windows\Temp\virtualbox\cert\vbox*.cer) do C:\Windows\Temp\virtualbox\cert\VBoxCertUtil add-trusted-publisher %%i --root %%i
```
instead of your changes on the same line.
This is also the preferred method described in "4.2.1.3. Unattended Installation" of the [documentation](https://www.virtualbox.org/manual/ch04.html#additions-windows).

**Comment by DanielKinsman** [comment]
Issue is #230, there is also another PR fixing this in a different way at #229.

**Comment by StefanScherer** [comment]
This PR looks better as we do not have to update the certs every x years in this repo. I‘ll try to find some time to test in the nect days and merge a fix.

**Comment by StefanScherer** [comment]
LGTM.
We can also get rid of oracle-cert.cer.

**Comment by Flauschbaellchen** [comment]
@StefanScherer I've opened another PR including the line from my first comment.
IMO it would be much cleaner, do respect changes like adding/removing certs and is also described as the preferred solution within the virtualbox documentation.

**Pull request merged**
