### PR TITLE
Addition of Parallels Guest Tools and URL changes

### PR DESCRIPTION
**Pull request by jcoutch**
I added the Parallels Guest Tools installation to vm-guest-tools.bat, and updated the 7-Zip URL's to use the non-SourceForge URL's currently on 7-Zip's website.

I also updated the URL for UltraDefrag, as the one in the compact script didn't appear to work.

### CODE REVIEW

**Comment by joefitzgerald** [comment]
LGTM - but why did we downgrade the version of ultradefrag?

**Comment by jcoutch** [comment]
I believe that was the newest version available...but can't check right now...SourceForge is down.  As soon as it's back up, I'll double check.

**Comment by jcoutch** [comment]
@joefitzgerald I updated the version number to 6.1.0, and verified the download link works.  Sorry about that.  Should be good to go now.  :-)

**Comment by kensykora** [comment]
:+1:

**Comment by joefitzgerald** [comment]
Thanks!

**Pull request merged**
