### PR TITLE
Increased ssh timeouts for win2k8 builds

### PR DESCRIPTION
**Pull request by jvogt**
The windows update process takes a very long time to bring up to date.

I could not get this to build in less than 4h even on fast internet connection.

### CODE REVIEW

**Comment by dwickern** [comment]
It took about 2.5 hours to run Windows updates for me on win2008

**Comment by mightydok** [comment]
Same proble, vote for merge

**Comment by rjhornsby** [comment]
+1. Even on a 1Gb connection, it's taking 5+ hours. In that case, I don't think the speed of the link is the issue. It's just there are so many patches that it takes win2008 that long to download, apply, reboot; download, apply, reboot; ...;

**Comment by StefanScherer** [comment]
Willing to merge as windows updates take ages on these old ISOs.

**Pull request merged**
