### PR TITLE
Replace expired vbox additions signing cert

### PR DESCRIPTION
**Pull request by rjhornsby**

### CODE REVIEW

**Comment by nap** [comment]
The certificate are already shipped with the `VBoxGuestAdditions.iso`:
The `oracle-cert.cer` can be removed and the `vs-guest-tools.bat` can be modified with the following definition for the `:virtualbox` label.

```
:virtualbox
move /Y C:\Users\vagrant\VBoxGuestAdditions.iso C:\Windows\Temp
cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\Windows\Temp\VBoxGuestAdditions.iso -oC:\Windows\Temp\virtualbox"
cmd /c C:\Windows\Temp\virtualbox\cert\VBoxCertUtil add-trusted-publisher C:\Windows\Temp\virtualbox\cert\vbox-sha1.cer --root C:\Windows\Temp\virtualbox\cert\vbox-sha1.cer
cmd /c C:\Windows\Temp\virtualbox\cert\VBoxCertUtil add-trusted-publisher C:\Windows\Temp\virtualbox\cert\vbox-sha256.cer --root C:\Windows\Temp\virtualbox\cert\vbox-sha256.cer
cmd /c C:\Windows\Temp\virtualbox\cert\VBoxCertUtil add-trusted-publisher C:\Windows\Temp\virtualbox\cert\vbox-sha256-r3.cer --root C:\Windows\Temp\virtualbox\cert\vbox-sha256-r3.cer
cmd /c C:\Windows\Temp\virtualbox\VBoxWindowsAdditions.exe /S
```

**Comment by alinefr** [comment]
I can confirm the fix works. It would be good to merge it.

**Comment by DanielKinsman** [comment]
Just ran into this problem as well, merging would be great.

**Comment by StefanScherer** [comment]
The PR #257 looks better as we do not have to update the certs every x years in this repo. I‘ll try to find some time to test in the nect days and merge a fix.

**Comment by StefanScherer** [comment]
Thanks. Fixed with #247 so we don't have to update the cert in this repo

**Pull request closed without merging**
