### PR TITLE
Update compact.bat

### PR DESCRIPTION
**Pull request by williamtsoi1**
fix url for sdelete

### CODE REVIEW

**Comment by StefanScherer** [comment]
@williamtsoi1 Thanks. Seems that the sysinternals team is moving to lower case. Got a similar error with ProcessExplorer.zip today with a chocolatey package procexp, but ProcessMonitor.zip still has CamelCase. Strange.

**Comment by StefanScherer** [comment]
I can curl both URL's and download the zip. Let's see how the sysinternals site behaves in one or two days how this situation stabilizes.

**Comment by StefanScherer** [comment]
Seems that lower case wins. ProcessMonitor.zip is now processmonitor.zip as well. So this LGTM!

**Comment by joefitzgerald** [comment]
Wait the sysinternal site is case sensitive? Seriously?

**Comment by StefanScherer** [comment]
@joefitzgerald 
procexp: https://chocolatey.org/packages/procexp#comment-2466241493
procmon: https://chocolatey.org/packages/procmon#comment-2467199321

But case sensitive? Do they switch to :penguin: ?

**Comment by joefitzgerald** [comment]
¯\_(ツ)_/¯

**Pull request merged**
