### PR TITLE
Added parallels builder to Windows 2012 R2

### PR DESCRIPTION
**Pull request by mewm**

### CODE REVIEW

**Comment by kensykora** [comment]
I don't have a licensed copy of Parallels. Since this is about 2 months stale, can you run a quick build against the latest and just confirm it works (with windows updates and all that)

**Comment by tbbuck** [comment]
For what it's worth, I've just successfully built a Windows 2012 R2 image using the parallels details here, and it's now happily running a Vagrant box. Looks like it still works :)

**Comment by mewm** [comment]
I don't have the license anymore, so I can't test it out @kensykora but it looks like @tbbuck got it properly working.

**Comment by tbbuck** [comment]
It's been a few hours of running now and it's still working as expected. I think you'd need a reminder to install the vagrant parallels plugin (https://github.com/Parallels/vagrant-parallels) - otherwise all looks very good :)

(and thanks for your work on this, you've saved me some pain!)

**Pull request closed without merging**
