### PR TITLE
Switch To WinRM

### PR DESCRIPTION
**Pull request by joefitzgerald**
- [ ] Use WinRM Exclusively
- [ ] Stop Installing OpenSSH
- [ ] Use Compress Post Processor Instead Of Vagrant Post Processor

Checklist of all templates ported to WinRM
- [x] Windows 2012 R2
- [x] Windows 2012 R2 Core
- [ ] Windows 2012
- [ ] Windows 2008 R2
- [ ] Windows 2008 R2 Core
- [x] Windows 10
- [ ] Windows 8.1
- [ ] Windows 7

### CODE REVIEW

**Comment by kensykora** [comment]
Wow, is this real life? :+1:

**Comment by StefanScherer** [comment]
Whoot!

**Comment by StefanScherer** [comment]
Removing rsync is just a consequence. "Get off of my vCloud ;-)" Internal joke, only needed for vagrant-vcloud plugin, but doesn't make sense here in upstream.

**Comment by pandrew** [comment]
Yay!

**Comment by StefanScherer** [comment]
I'll test the windows_10.json in a few minutes and remove the SSH parts there, too.

**Comment by StefanScherer** [comment]
@joefitzgerald my first Windows 10 build for Fusion was fine, but I left the Vagrant Post Processor in the json template. What is your reason to switch to the Compress Post Processor?
May I push the commit for windows_10.json + answer_files/10/Autounattend.xml into this branch?
Starting VirtualBox build now...

**Comment by joefitzgerald** [comment]
@StefanScherer Of course, feel free to push to that branch.

I decided to switch to the compress post processor because it encourages people to build a single based image (with Windows updates applied) that they can then use to further iterate via the vmware-vmx or virtualbox-ovf builders. I don't think we need to push people straight over to vagrant, particularly with the flux associated with https://ottoproject.io.

**Comment by StefanScherer** [comment]
OK, I got it. :+1: So I'll adjust the post processor before the push.

**Comment by Real2014** [comment]
Seems that the WinRM instead of SSH finally works. Great WORK and thank you! I always had the problem that the windows ssh packer scripts didn't work on German ISO. Now with using WinRM the problem should be part of history :+1:

**Comment by pknath19** [comment]
I have tested this and everything works great.  The only issue is WinRM has slow file transport speeds.  I tested this with an ISO and it took >  6hrs to complete.  I did some research and others are having the same issues with WinRM.  https://github.com/packer-community/winrmcp/pull/6  and https://github.com/mitchellh/packer/issues/2648#issuecomment-170756293. Users beware of slow speeds in WinRM transports.

**Comment by StefanScherer** [comment]
Worth reading http://www.hurryupandwait.io/blog/whats-new-in-the-ruby-winrm-gem-15
It's Ruby, but someone may have a look at it to do the same in GO. -> PSRP

/cc @mwrock ;-)

**Comment by sneal** [comment]
Closing in favor of #200

**Comment by martinmosegaard** [comment]
Can I ask here on the current status of WinRM and packer? I am trying to use the winrm communicator with Windows 2008, but it fails with a `wsarecv` error. I can see that the templates in this repository still use ssh instead of the winrm communicator, so it is not clear to me what the preferred way is.

**Pull request closed without merging**
