### PR TITLE
Update OpenSSH to version 6.7p1-2

### PR DESCRIPTION
**Pull request by StefanScherer**
I've just seen [here](http://www.mls-software.com/opensshd.html) that there is a newer version of OpenSSH. In Version 6.6.1p1-3 the 32bit and 64bit versions are inside one installer, so there is only one download link.

### CODE REVIEW

**Comment by avtar** [comment]
Could someone please comment on the status of this PR?

**Comment by stefanschererseal** [comment]
Oh, a little outdated. I'll rebase and update the download link.

**Comment by StefanScherer** [comment]
In develop branch the `openssh.ps1` already downloads the OpenSSH 6.7p1-1.

In the meantime a new vagrant-serverspec has been released, and as well new versions of Vagrant. So I'll retest it, perhaps this weekend and see if this ssh key problem still exists.

**Comment by avtar** [comment]
Thanks, @StefanScherer!

**Comment by joefitzgerald** [comment]
LGTM, please :ship: @StefanScherer!

**Comment by StefanScherer** [comment]
I have updated the PR to install OpenSSH 6.7p1-2 and tested it with a windows_7 box without updates and VirtualBox. The packer build works. So this is ready :ship:  into `develop` branch.

**Pull request merged**
